// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://godcfwqxkdcpsbdhmxws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZGNmd3F4a2RjcHNiZGhteHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MzQ2OTQsImV4cCI6MjA2MTUxMDY5NH0.T1n_fxzlSIviTQqmdq6_7Fz99siijRmXoa-c_V73AUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);